"""initial schema

Revision ID: 6ca8998abe76
Revises: 
Create Date: 2026-01-11 11:31:52.477232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ca8998abe76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('wo_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('context_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('context_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('wo_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('input_files',
    sa.Column('input_file_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('wo_id', mysql.TEXT(), nullable=False),
    sa.Column('original_filename', mysql.TEXT(), nullable=False),
    sa.Column('storage_uri', mysql.TEXT(), nullable=False),
    sa.Column('file_hash', mysql.TEXT(), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('input_file_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('llm_calls',
    sa.Column('llm_call_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('run_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('qs_number', mysql.TEXT(), nullable=True),
    sa.Column('prompt_hash', mysql.TEXT(), nullable=False),
    sa.Column('response_hash', mysql.TEXT(), nullable=False),
    sa.Column('tokens_in', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tokens_out', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('model_name', mysql.TEXT(), nullable=False),
    sa.Column('temperature', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('llm_call_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('runs',
    sa.Column('run_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('wo_id', mysql.TEXT(), nullable=False),
    sa.Column('wo_version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('wo_context_hash', mysql.TEXT(), nullable=False),
    sa.Column('input_file_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('model_name', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.TEXT(), nullable=False),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('started_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('run_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('work_orders_history',
    sa.Column('wo_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('context_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('context_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('archived_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('wo_id', 'version'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('change_events',
    sa.Column('change_event_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('run_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('wo_id', mysql.TEXT(), nullable=False),
    sa.Column('qs_number', mysql.TEXT(), nullable=False),
    sa.Column('list_field', mysql.TEXT(), nullable=True),
    sa.Column('jurisdiction', mysql.TEXT(), nullable=True),
    sa.Column('change_type', mysql.TEXT(), nullable=False),
    sa.Column('target', mysql.TEXT(), nullable=True),
    sa.Column('target_identifier', mysql.TEXT(), nullable=True),
    sa.Column('field_path', mysql.TEXT(), nullable=True),
    sa.Column('old_value', mysql.TEXT(), nullable=True),
    sa.Column('new_value', mysql.TEXT(), nullable=True),
    sa.Column('reason_code', mysql.TEXT(), nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=False),
    sa.Column('evidence_text', mysql.TEXT(), nullable=False),
    sa.Column('effective_date', sa.DATE(), nullable=True),
    sa.Column('source_document', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('change_event_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('run_artifacts',
    sa.Column('artifact_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('run_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('artifact_type', mysql.TEXT(), nullable=False),
    sa.Column('storage_uri', mysql.TEXT(), nullable=False),
    sa.Column('artifact_hash', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('artifact_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_artifacts')
    op.drop_table('change_events')
    op.drop_table('work_orders_history')
    op.drop_table('runs')
    op.drop_table('llm_calls')
    op.drop_table('input_files')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
